# This code is used to generate histograms for data generated by HOMER. The data is used to identify number of reads with respect to TSS in the Human genome (hg19)

## COMMANDS FOR HOMER
# makeTagDirectory <directory_name> <bamfile>
# annotatePeaks.pl tss hg19 -size 1000 -hist 2 -d <directories to tag files> > <outputfile>


## Load libraries
library(ggplot2)
library(reshape)

# Load data
path <- "./HOMER/density_plots_manuscript/highmag_HCFC1-HepG2IR-HepG2-Pol2.txt"
filename <- "SHSIR_500_results.txt"

data <- read.delim(file.path(path), sep="\t", header=T)

df <- data[,c(1,2,5,8)]
names(df) <- c("distance", "IR", "Pol2", "HCFC1")
df.melt <- melt(df, id=c("distance"))
names(df.melt)[2] <- "IP"

ggplot(df.melt) + 
  geom_line(aes(x=distance, y = value, color = IP), size=1.5) + 
  theme_bw() +
  theme( legend.position="none",
        plot.title = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.25))) +
  ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak") +
  scale_color_manual(values=c( "darkgreen","#00009B"))

### Overlay plots with two scales ####

library(ggplot2)
library(gtable)
library(grid)
library(RColorBrewer)


# Load data
path <- "./HOMER/density_plots_manuscript/lowmag_HepG2IR-HepG2-Pol2.txt"
data <- read.delim(file.path(path), sep="\t", header=T)
cbPalette <- brewer.pal(9, "Set1")

# two plots
df <- data[,c(1,2,5)]
names(df) <- c("distance", "IR", "Pol2")

grid.newpage()

p1 <-  ggplot(df) + 
  geom_line(aes(x=distance, y = IR), size=1.5, color=cbPalette[1]) + 
  theme_bw() +
  theme( plot.title = element_text(size = rel(1.5)),
         axis.title = element_text(size = rel(1.5)),
         axis.text = element_text(size = rel(1.25)),
         panel.grid.minor = element_blank(),
         panel.grid.major = element_blank()) +
  geom_vline(xintercept=c(0), linetype="dashed", color="grey")
  ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak (IR)") 


p2 <- ggplot(df) + 
  geom_line(aes(x=distance, y = Pol2), size=1.5, color=cbPalette[2]) + 
  ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak") +
  theme_bw() +
  theme( plot.title = element_text(size = rel(1.5)),
         axis.title = element_text(size = rel(1.5)),
         axis.text = element_text(size = rel(1.25))) %+replace% 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = NA))
# theme(panel.background = element_rect(fill = NA))

# extract gtable
g1 <- ggplot_gtable(ggplot_build(p1))
g2 <- ggplot_gtable(ggplot_build(p2))

# overlap the panel of 2nd plot on that of 1st plot
pp <- c(subset(g1$layout, name == "panel", se = t:r))
g <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, 
                     pp$l, pp$b, pp$l)

# axis tweaks
ia <- which(g2$layout$name == "axis-l")
ga <- g2$grobs[[ia]]
ax <- ga$children[[2]]
ax$widths <- rev(ax$widths)
ax$grobs <- rev(ax$grobs)
ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths) - 1)
g <- gtable_add_grob(g, ax, pp$t, length(g$widths) - 1, pp$b)

# draw it
grid.draw(g)


### Three plots ####

# Load data
path <- "./HOMER/density_plots_manuscript/highmag_HCFC1-HepG2IR-HepG2-Pol2.txt"
data <- read.delim(file.path(path), sep="\t", header=T)

# two plots
df <- data[,c(1,2,5,8)]
names(df) <- c("distance", "IR", "Pol2", "HCFC1")

grid.newpage()

p1 <-  ggplot(df) + 
  geom_line(aes(x=distance, y = IR), size=1.5, color="#CC6666") + 
  theme_bw() +
  theme( plot.title = element_text(size = rel(1.5)),
         axis.title = element_text(size = rel(1.5)),
         axis.text = element_text(size = rel(1.25))) +
  ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak (IR)") 

# two plots with one axis
df <- data[,c(1,5,8)]
names(df) <- c("distance", "Pol2", "HCFC1")
df.melt <- melt(df, id=c("distance"))
names(df.melt)[2] <- "IP"


p2 <- ggplot(df.melt) + 
  geom_line(aes(x=distance, y = value, color=IP), size=1.5) + 
  ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak") +
  scale_color_manual(values=c( "darkgreen","#00009B")) +
  theme_bw() +
  theme( legend.position="none",
         plot.title = element_text(size = rel(1.5)),
         axis.title = element_text(size = rel(1.5)),
         axis.text = element_text(size = rel(1.25))) %+replace% 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = NA))
#  theme(panel.background = element_rect(fill = NA))


# extract gtable
g1 <- ggplot_gtable(ggplot_build(p1))
g2 <- ggplot_gtable(ggplot_build(p2))

# overlap the panel of 2nd plot on that of 1st plot
pp <- c(subset(g1$layout, name == "panel", se = t:r))
g <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, 
                     pp$l, pp$b, pp$l)

# axis tweaks
ia <- which(g2$layout$name == "axis-l")
ga <- g2$grobs[[ia]]
ax <- ga$children[[2]]
ax$widths <- rev(ax$widths)
ax$grobs <- rev(ax$grobs)
ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths) - 1)
g <- gtable_add_grob(g, ax, pp$t, length(g$widths) - 1, pp$b)

# draw it
grid.draw(g)



## Genomatix files: Density Plots using only overlapping regions

# Load data
path <- "./HOMER/genomatix/Pol2_HepG2IR.txt"
data <- read.delim(file.path(path), sep="\t", header=T)
cbPalette <- brewer.pal(9, "Set1")

# two plots
df <- data[,c(1,2,5)]
names(df) <- c("distance", "IR", "Pol2")

grid.newpage()

p1 <-  ggplot(df) + 
  geom_line(aes(x=distance, y = IR), size=1.5, color=cbPalette[1]) + 
  theme_bw() +
  theme( plot.title = element_text(size = rel(1.5)),
         axis.title = element_text(size = rel(1.5)),
         axis.text = element_text(size = rel(1.25)),
         panel.grid.minor = element_blank(),
         panel.grid.major = element_blank()) +
  geom_vline(xintercept=c(0), linetype="dashed", color="grey") +
ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak (IR)") 


p2 <- ggplot(df) + 
  geom_line(aes(x=distance, y = Pol2), size=1.5, color=cbPalette[2]) + 
  ggtitle('') +
  xlab("Distance from TSS") + ylab("Tags per bp per peak") +
  theme_bw() +
  theme( plot.title = element_text(size = rel(1.5)),
         axis.title = element_text(size = rel(1.5)),
         axis.text = element_text(size = rel(1.25))) %+replace% 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = NA))
# theme(panel.background = element_rect(fill = NA))

# extract gtable
g1 <- ggplot_gtable(ggplot_build(p1))
g2 <- ggplot_gtable(ggplot_build(p2))

# overlap the panel of 2nd plot on that of 1st plot
pp <- c(subset(g1$layout, name == "panel", se = t:r))
g <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, 
                     pp$l, pp$b, pp$l)

# axis tweaks
ia <- which(g2$layout$name == "axis-l")
ga <- g2$grobs[[ia]]
ax <- ga$children[[2]]
ax$widths <- rev(ax$widths)
ax$grobs <- rev(ax$grobs)
ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths) - 1)
g <- gtable_add_grob(g, ax, pp$t, length(g$widths) - 1, pp$b)

# draw it
grid.draw(g)



